<?php if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::HORIZONTAL): 		?>
<?php /*
<link media="all" href="<?php echo $this->getSkinUrl('sm/megamenu/css/horizontal/black/megamenu.css');?>" type="text/css" rel="stylesheet">
*/ ?>
<?php elseif($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::VERTICAL):	?>

<link media="all" href="<?php echo $this->getSkinUrl('sm/megamenu/css/vertical/black/megamenu.css');?>" type="text/css" rel="stylesheet">
<?php endif	?>