<?php
	global $var_yttheme;
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="block-feature-products">
	<!--<div class="block-title"><h3 style=""><?php //echo $this->block_title; ?></h3></div>
	<div class="des-block">Lorem ipsum dolor sit amet, consectetur adipiscing elit ac lobortis lacus</div>-->
    <div class="block-content">
    	<?php if(!$_productCollection->count()): ?>
        	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: 
		$row = 0;
        $col= 0;
        $count = 1;
		$i=0;
		$j=0;
		$_collectionSize = $_productCollection->count();
		foreach($_productCollection as $_product): $j++;
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
			$isBestProduct =($_product->getResource()->getAttribute('best') AND $_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';			
			$this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper'); 
		?>
			<?php if ($i++==0): ?>
			<div class="products-grid category-products">				
			<?php endif ?>
			
				<div class="item <?php echo "item-".$j; ?> clearfix">
							<div class="item-inner">
								<div class="item-box">
									<?php if ($this->product_image_disp): ?>
									<div class="product-image">																		
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-imgs"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($this->product_image_width,$this->product_image_height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	                                                                            
                                    <?php if ($this->product_description_disp){ ?>
                                    		<div class="item-description">                                        	
                                            <?php 
												if(strlen($_helper->productAttribute($_product, $_product->getshort_description(), 'short_description')) > 120){
													echo substr($_helper->productAttribute($_product, $_product->getshort_description(), 'short_description'), 0, 120) .' ...';
												}else{
													echo $_helper->productAttribute($_product, $_product->getshort_description(), 'short_description');
												}
											?>
                                       	 	</div>
                                     <?php } ?>                                 	                                 
									</div>
									<?php endif; ?>                                    
									</div> <?php //[end]  item-box	?>
                                    
                                <div class="item-box-footer">	
                                	<?php if ($this->product_title_disp){ ?>
										<h2 class="product-name">
										<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
										<?php
											if ( $this->product_title_max_length > 0){
												$_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
											}
										?>											
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
										<?php //echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                                        <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                                        </a>
									</h2>
									<?php  } ?>	
                                	<?php if ($this->product_price_disp): ?>
                            		<div class="price-wrapper">											
										<div class="price-block"><?php echo /*'<span>Price: </span>'.*/$this->getPriceHtml($_product, true, false) ?></div>										
									</div>	
                                    <?php endif; ?> 
                                    <?php if ($this->product_rating_summary): ?>
                                     <?php                                           
                                     //if($_product->getRatingSummary()): ?>
                                    <?php  echo $this->getReviewsSummaryHtml($_product, false, true); ?>
                                    <?php //endif; 
                                        //echo $this->getReviewsSummaryHtml($_product, false, true);
                                        
                                    ?>
                                    <?php endif; ?> 
                                	<div class="cart-wishlist">	
                                    <?php if ($this->helper('wishlist')->isAllow() AND $this->product_addtowishlist) : ?>
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn-wishlist">
                                            <span class="icon-wishlist"></span>
                                            <span class="icon-wishlist-text">Wishlist</span>
                                        </a>
									<?php endif; ?>																						
								  	<?php if ($this->product_cart_or_status){ ?>											
												<?php if($_product->isSaleable()): ?>
													<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                    	<span class="icon-cart"></span>
                                                        <span class="icon-cart-text">Add To Cart</span>
                                                    </a>
												<?php else: ?>
													<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php endif; ?>											
											<?php } ?>	
                                 			                                 
                               </div>
								</div>    																	
							</div> <?php //[end]  item-inner	?>
						</div>	<?php //[end]  item	?>
					
 			<?php if ($i==$_collectionSize): ?>			
        </div> <?php //[end]  products-grid	?>
        <?php endif ?>
        <?php endforeach; ?>
    <?php endif; ?>
	</div>
</div>
