<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="block for-menu">
    <div class="yt-products-container-menu">
    	<?php if(!$_productCollection->count()): ?>
        	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: 
		$row = 0;
        $col= 0;
        $count = 1;
		foreach($_productCollection as $_product):
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			$isBestProduct =($_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';                				
            if( ($count==1) || (($count-1)%$this->getNumColumns()== 0) ){
                $row++;
            ?>
            <ul class="products-grid products cols-<?php echo $this->getNumColumns().' row-'.$row ; ?>">
            <?php
            }?>
                <li class="item">
                    <div class="item-inner">
                    	<div class="item-box">
							<?php
                            if ($now>=$newsFrom && $now<=$newsTo){
                                echo "<span class='newproduct-grid'>new</span>";
                                //echo $now.' -- '.$newsFrom.' -- '.$newsTo;
                            }
                            if ($specialprice){
                                echo "<span class='saleoff-grid'>sale off</span>";
                            }
							if ($isBestProduct){
								echo "<span class='bestproduct-grid'>best</span>";
							}							
                            ?>
                            <?php if ($this->product_image_disp): ?>
                            <div class="product-image">
                            	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                            </div>
                            <?php endif; ?>
                            <?php if ($this->product_price_disp): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
                            <?php endif; ?>
                        </div>
                        
                        <div class="item-box-hover">
                            <?php if ($this->product_cart_or_status): ?>
                            <?php if($_product->isSaleable()): ?>
                                <a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);<?php //echo $this->getAddToCartUrl($_product) //allow add product to cart and then redirect to cart page ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a>
                            <?php else: ?>
                                <span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                            <?php endif; ?>
                            <?php endif; ?>
                            <div class="actions">
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                        
                        
                        <?php if ($this->product_title_disp): ?>
                        <h2 class="product-name">
                        	<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <?php
                                if ( $this->product_title_max_length > 0){
                                    $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
                                }
                            ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
                         </h2>
                         <?php endif; ?>
                         <?php
							if( $this->product_rating_summary ){
								Mage::getModel('review/review')->getEntitySummary($_product, Mage::app()->getStore()->getId());
								if ( $_product->getRatingSummary() ){
									echo $this->getReviewsSummaryHtml($_product);
								}
							} 
						?>
                        <?php if ($this->product_description_disp): ?>
                        <div class="item-description">
                            <?php
                                $product_description_src = in_array($this->product_description_src, array('short_description', 'description')) ? $this->product_description_src : 'short_description';
                                $product_description = $_helper->productAttribute($_product, $_product->$product_description_src, $product_description_src);
                                
                                if ( $this->product_description_strip_tags ){
                                    $allow_tags = $this->product_description_keep_tags ? $this->product_description_keep_tags : null;
                                    $product_description = $this->stripTags( $product_description,  $allow_tags, true);
                                }
                                
                                if ( $this->product_description_max_length > 0){
                                    $product_description = Mage::helper('core/string')->truncate($product_description, (int)$this->product_description_max_length);
                                }
                                
                                echo $product_description;
                            ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                        <?php endif; ?>
                	</div>
                </li>
            <?php
			//echo $count.' '.$_productCollection->count().' '.$this->getNumColumns();
			if( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) ){
				?>
				</ul>
				<?php
			}
			$count = $count+1;
			?>
        <?php endforeach; ?>
    <?php endif; ?>
	</div>
</div>
