<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
	$descLength = $this->product_description_max_length;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="category-products">
	<?php if ($this->title){ ?>
	<?php 
		//$arr_word =  $this->title ? explode(' ',$this->title) : "";
		//$join_word = array_shift($arr_word).' <span>'.implode(' ',$arr_word).'</span>';
	 ?>	
	<div class="block-title"><strong><?php //echo $join_word; ?><?php echo $this->title ?></strong></div>
	<?php } ?>
    <div class="yt-products-container">
    <?php 
	if(!$_productCollection->count()){ ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
     <?php 
	}else{
		$row = 0;
        $col= 0;
        $count = 1;
		$i=0; 
		$_collectionSize = $_productCollection->count();
		foreach($_productCollection as $_product){
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			$isBestProduct =($_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';                				
            ?>
			<?php if ($i++==0){ ?>
				<div class="products-grid">
					<?php } ?>
							<div class="item <?php echo ( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) )?"last":""; ?>">
								<div class="item-inner <?php /*bgcolor2-hover */ ?>">
					
									<div class="item-box">
                                    <?php if($_product->isSaleable()): ?>
											<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);<?php //echo $this->getAddToCartUrl($_product) ?>" class="btn-cart icon-circle bgcolor fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="icon-cart"></span></a>
										<?php else: ?>
											<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
										<?php endif; ?>	
										<?php
										if ($now>=$newsFrom && $now<=$newsTo){
											echo "<span class='newproduct-grid'>new</span>";
											//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
										}
										if ($specialprice){
											echo "<span class='saleoff-grid'>sale off</span>";
										}
										if ($isBestProduct){
											echo "<span class='bestproduct-grid'>best</span>";
										}										
										?>
										<div class="product-image">
											<a class="link-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" ><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
											<?php /*	
											<div class="item-box-hover ">
												<?php if($_product->isSaleable()): ?>
													<a title="<?php echo $this->__('Add to Cart') ?>" href="<?php //echo $this->getAddToCartUrl($_product) //allow add product to cart and then redirect to cart page ?>" class="btn-cart fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></a>
												<?php else: ?>
													<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
												<?php endif; ?>	
												
																					
												<a class="readmore fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><i class="icon-plus-circle"></i><span class="bgmask"></span></a>
												<?php //if($_product->getRatingSummary()): ?>            
													<?php //echo $this->getReviewsSummaryHtml($_product, 'short', true) ?>
												<?php //endif; ?>	
												<div class="actions">
													<ul class="add-to-links">
														<?php if ($this->helper('wishlist')->isAllow()) : ?>
															<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
														<?php endif; ?>
														<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
															<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
														<?php endif; ?>
													</ul>
												</div>
												
											</div>	
											*/ ?>											
										</div>
                                        
										<?php //echo $this->getPriceHtml($_product, true) ?>
									</div>
									<div class="item-box-footer">
										<h2 class="product-name <?php /* font1 */ ?>">
											<a class="fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
											<?php 
											if(strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 15){
												echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 15) .' ...';
											}else{
												echo $_helper->productAttribute($_product, $_product->getName(), 'name');
											}
											?>
											</a>
										</h2>	
										<?php /* 		
										<div class="desc std clearfix">
											<?php 
												if(strlen($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')) >$descLength){
													echo substr( $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 0, $descLength) .' ...';
												}else{
													echo  $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description');
												}
											?>						
										</div>	 
										*/ ?>																	
										<?php echo $this->getPriceHtml($_product, true) ?>
										<?php /* <a class="readmore fontcolor" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><?php echo $this->__('More Detail')  ?></a> */ ?>																					
																		
									</div>
									<?php /*<span class="inner-border border-hover"></span>*/ ?>
								</div>
							</div>
					<?php // if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
					<?php if ($i==$_collectionSize){ ?>
				</div><?php /*	end div products-grid	*/ ?>
<?php
 			} 	?>
<?php
		}	?>
<?php 	
	} 	?>
	</div>
</div>
