<?php if($config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::ANIMATION OR $config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::TOGGLE):?>
	<?php echo $this->getScriptTags();?>
	
	<script type="text/javascript">
	<?php if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::HORIZONTAL): 		?>
	// <![CDATA[ 
	$jsmart.fn.getOffsetRight=function(){	//this is object that need get offset right	
		offset_right = $jsmart(this).offset().left + $jsmart(this).outerWidth();	
		return offset_right;
	}
	$jsmart.fn.getOffsetLeft=function(){	//this is object that need get offset right	
		offset_right = $jsmart(this).offset().left;	
		return offset_right;
	}	
	$jsmart.fn.setOffsetElement = function(){	//this is div child of LI.sm_megamenu_lv1 object that need "set offset left for div has align:left" and "set offset right for div has align:right"
			
			offset_right_class_sm_megamenu_menu =  $jsmart('#<?php echo $uq?>').getOffsetRight();
			offset_left_class_sm_megamenu_menu = $jsmart('#<?php echo $uq?>').getOffsetLeft();	
			
			if(!$jsmart(this).hasClass('sm_megamenu_align_right')){
				
				px_exceed_right_side_menu = $jsmart(this).offsetParent().offset().left+ $jsmart(this).outerWidth() - offset_right_class_sm_megamenu_menu;
				//console.log(px_exceed_right_side_menu);
				if(px_exceed_right_side_menu>0){
					//$jsmart(this).css({'left':-px_exceed_right_side_menu});
					$jsmart(this).css({'left':'0'});
				}
				else{
					$jsmart(this).css({'left':'0'});
				}
			}
			else{
				
				px_exceed_left_side_menu = $jsmart(this).offsetParent().getOffsetRight() - $jsmart(this).outerWidth() - offset_left_class_sm_megamenu_menu ;
				
				if(px_exceed_left_side_menu>0){				
					$jsmart(this).css({'left':'auto', 'right':'0px'});
				}
				else{
					$jsmart(this).css({'left':'auto', 'right':px_exceed_left_side_menu});
				}						
			}	
	}
	
		<?php if($config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::ANIMATION):?>
			$jsmart(window).load(function() {	//init
				effect_duration = <?php echo $config['effect_duration']; ?>;
				if(effect_duration <= 0){
					effect_duration = <?php echo Sm_Megamenu_Helper_Default::EFFECT_DURATION ?>;
				}
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('div').each(function(i,e){
					$jsmart(e).setOffsetElement();		
				});				
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('div').css({'display':'none'});
				// $jsmart('li.sm_megamenu_lv1').children('div').css({'left':'0px', 'display':'none'});
				// $jsmart('li.sm_megamenu_lv1').children('div.sm_megamenu_align_right').css({'left':'auto', 'display':'none', 'right':'0px'});
				
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').hover(
					function(e){	$jsmart(this).children('div').stop(true,true).delay(180).slideDown(effect_duration);	},
					function(e){	$jsmart(this).children('div').stop(true,true).delay(0).slideUp(0);	}
				);
			});
		<?php endif?>	
		<?php if($config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::TOGGLE):?>
			$jsmart(function() {
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('div').each(function(i,e){
					$jsmart(e).setOffsetElement();
					ul_sm_megamenu_menu_height = $jsmart(this).offsetParent().outerHeight();
					$jsmart(this).css({'top':ul_sm_megamenu_menu_height+3});
				});				
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('div').css({'display':'none'});			
				// $jsmart('li.sm_megamenu_lv1').children('div').css({'left':'0px', 'display':'none'});
				// $jsmart('li.sm_megamenu_lv1').children('div.sm_megamenu_align_right').css({'left':'auto', 'display':'none', 'right':'0px'});
				// $tab_actived ='';
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('.sm_megamenu_head').click(
					function(e){	
						if(!$jsmart(this).next().length || $jsmart(this).next().is(':hidden')===true){
							$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('div').hide();
							$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').children('.sm_megamenu_head').removeClass('sm_megamenu_actived');
						}						
						$jsmart(this).toggleClass("sm_megamenu_actived");
						$jsmart(this).next().toggle();	
					}
				);
			});		
		<?php endif?>	
	<?php elseif($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::VERTICAL):	?>
		<?php if($config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::ANIMATION):?>
			$jsmart(function() {
				// $jsmart('li.sm_megamenu_lv1').children('div').css({'left':'145px', 'display':'none'});
				effect_duration = <?php echo $config['effect_duration']; ?>;
				if(effect_duration <= 0){
					effect_duration = <?php echo Sm_Megamenu_Helper_Default::EFFECT_DURATION ?>;
				}				
				$jsmart('#<?php echo $uq?> li.sm_megamenu_lv1').hover(
					function(e) {  
						w = getWbc($jsmart(this).children('div'));
						// console.log(w);
						if(w){
							// w = $jsmart(this).children('div').outerWidth()+'px';
							$jsmart(this).children('div').css({opacity:'1',width:'0px'});
							$jsmart(this).children('div').stop(true,true).animate({
								width: w, 
								opacity:'1'
							}, effect_duration );
						}
					},
					function(e) {
						$jsmart(this).children('div').stop(true,true).animate({
							width: '0px',
							opacity:'0'
						}, 300);
					});
			});	
			// get Width by column
			function getWbc(e){	//get width by class class_width, return number px
				json_class_width = {
						'sm_megamenu_dropdown_1column': '145',
						'sm_megamenu_dropdown_2columns': '300',
						'sm_megamenu_dropdown_3columns': '455',
						'sm_megamenu_dropdown_4columns': '610',
						'sm_megamenu_dropdown_5columns': '765',
						'sm_megamenu_dropdown_6columns': '920',
						'sm_megamenu_dropdown_fullwidth': '920'
					};
				for(var key in json_class_width){
					if ( json_class_width.hasOwnProperty ( key ) ){
						// alert( key ‘=>’ json_class_width [ key ] );
						if(e.hasClass(key)){
							return json_class_width[ key ];
						}
					}
				}
				return false;	
			}
		<?php endif?>	
		<?php if($config['effect']==Sm_Megamenu_Model_System_Config_Source_ListEffect::TOGGLE):?>
			$jsmart(function() {
				$jsmart('.sm_megamenu_wrapper_vertical_menu #<?php echo $uq?> li.sm_megamenu_lv1').children('div').each(function(i,e){
					$jsmart(this).css({'top':0});
				});			
				$jsmart('.sm_megamenu_wrapper_vertical_menu #<?php echo $uq?> li.sm_megamenu_lv1').children('div').css({'left':'190px', 'display':'none'});
				// $jsmart('li.sm_megamenu_lv1').children('div.sm_megamenu_align_right').css({'left':'auto', 'display':'none', 'right':'0px'});
				// $tab_actived ='';
				$jsmart('.sm_megamenu_wrapper_vertical_menu #<?php echo $uq?> li.sm_megamenu_lv1').children('.sm_megamenu_head').click(
					
					function(e){	
						if(!$jsmart(this).next().length || $jsmart(this).next().is(':hidden')===true){
							$jsmart('.sm_megamenu_wrapper_vertical_menu #<?php echo $uq?> li.sm_megamenu_lv1').children('div').hide();
							$jsmart('.sm_megamenu_wrapper_vertical_menu #<?php echo $uq?> li.sm_megamenu_lv1').children('.sm_megamenu_head').removeClass('sm_megamenu_actived');
						}						
						$jsmart(this).toggleClass("sm_megamenu_actived");
						$jsmart(this).next().toggle();	
					}
				);
			});				
		<?php endif?>		
	<?php endif	?>
	// ]]> 
	</script>

<?php endif ?>