<?php
/*------------------------------------------------------------------------
 # SM Responsive Listting - Version 1.0
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$smarthelper = Mage::helper('responsivelisting/utils');
$_helper = $this->helper('catalog/output');
$list = $this->getProduct();
$options = $this->getConfigObject(); ?>

 <?php
if(isset($list['items'])) {
foreach($list['items']  as $item){ 
	$_product = Mage::getModel("catalog/product")->load($item->id);
	$now = date("Y-m-d");
	$newsFrom= substr($_product->getData('news_from_date'),0,10);
	$newsTo=  substr($_product->getData('news_to_date'),0,10);
	$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
	$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
	$saleoff= round(($price - $specialprice)/$price*100) ;
	$isBestProduct =($_product->getResource()->getAttribute('best') AND $_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';
	$this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper');
?>
<div class="respl-item first-load category-<?php echo $item->catid; ?>" data-created="<?php echo strtotime($item->createdfrom); ?>" data-price="<?php echo $item->hits; ?>" data-title="<?php echo trim(strtoupper($item->title)); ?>" data-id="<?php echo $item->id; ?>" data-catid="<?php echo $item->catid ;?>">
		<div class="item-inner">
		<div class="item-inner2">
        	<?php if( $options->item_cat_display == 1 ) {	?>
					<?php 
					$categoryIds = $_product->getCategoryIds();
					if (is_array($categoryIds) and count($categoryIds) > 1) {
						$_cat = Mage::getModel('catalog/category')->load($categoryIds[0]);
					};
					?>									
					<a class="cat-name" href="<?php echo $_cat->getUrl() ?>"><?php echo $_cat->getName(); ?></a>		
			<?php } ?>
            <div class="item-box-header">
            	<?php if( $options->item_title_display == 1 ){?>
					<h2 class="product-name">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <?php
                            if ( $this->product_title_max_length > 0){
                                $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
                            }
                        ?>											
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
					</h2>
				<?php }?> 
                <?php if( $options->item_price_disp== 1) { ?>               
                    <div class="price-wrapper">											
                            <?php echo /*'<span>Price: </span>'.*/$this->getPriceHtml($_product, true, false) ?>
                    </div>
                <?php } ?>
            </div>
            <div class="item-box">
                <div class="product-image">
                    <?php
                    if ($now>=$newsFrom && $now<=$newsTo){ 	?>
                        <div class='new-item'><span><?php echo $this->__('New'); ?></span></div>
                    <?php }
                    if ($specialprice){ ?>
                        <div class='sale-item'><span><?php echo $saleoff.'%<br />'.$this->__('off');?></span></div>
                    <?php }
                    if ($isBestProduct){ ?>
                        <div class='best-item'></div>
                    <?php }
                    ?>								
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-imgs">
							<img src="<?php echo $item->image;?>" alt="<?php echo $item->title;?>" />
					</a>                 									                                											
                    <div class="bg-hover">
                    	<?php if( $options->item_desc_display == 1 ) {?>
                        	<!--<div class="item-description">                                        	        
								<?php //echo substr($_product->getdescription(),0,80).' ...'; ?>
							</div>-->
                            <?php if($_product->getshort_description()) { ?>
                            <div class="item-short-desc">
                            	<?php echo $_product->getshort_description(); ?>
                            </div> 
                            <?php } ?>                           
						<?php }?>                      
                        <div class="ratings-wishlist">                       
                        <?php if( $options->item_review_disp ){ ?>
                        	<div class="ratings-wrap">
                        	<?php
								$product = Mage::getModel('catalog/product')->load($_product->getId());
								 
								if($this->_reviewsHelperBlock->getSummaryHtml($product, false, false)){
									echo $this->_reviewsHelperBlock->getSummaryHtml($product, false, false);
								}
								//echo $item->review_html;  
								// false, true: show Be first review...
							?>
                             </div>
                             
						<?php } ?>	
                        <?php if ($this->helper('wishlist')->isAllow() ) : ?>
							<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn-wishlist" title="<?php echo $this->__('Add to Wishlist'); ?>"><?php echo $this->__('Add to Wishlist'); ?></a>
						<?php endif; ?>                        
                        </div>                                     
                    </div>
                                                        
                </div>
            </div>
            <div class="item-box-footer">	
            <div class="item-box-footer-inner">
            	<?php if( $options->item_title_display == 1 ){?>
					<h2 class="product-name">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <?php
                            if ( $this->product_title_max_length > 0){
                                $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
                            }
                        ?>											
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
					</h2>
				<?php }?> 
                <?php if( $options->item_price_disp== 1) { ?>               
                    <div class="price-wrapper">											
                            <?php echo /*'<span>Price: </span>'.*/$this->getPriceHtml($_product, true, false) ?>
                    </div>
                <?php } ?>
                <?php if( $options->item_review_disp ){ ?>
                    <div class="ratings-wrap">
                    <?php
                        /* $product = Mage::getModel('catalog/product')->load($_product->getId());
                         
                        if($this->_reviewsHelperBlock->getSummaryHtml($product, false, false)){
                            echo $this->_reviewsHelperBlock->getSummaryHtml($product, false, false);
                        }*/
						echo $item->review_html; 
                    ?>
                     </div>                             
				<?php } ?>	
                <?php if( $options->item_desc_display == 1 ) {?>
                   
                    <?php if($_product->getshort_description()) { ?>
                    <div class="item-short-desc">
                        <?php //if(strlen($_product->getshort_description()) >200){
							//echo substr($_product->getshort_description(),0,200); 
						//} else {
							echo $_product->getshort_description(); 
							//}
						 ?>
                    </div> 
                    <?php } ?>                           
						<?php }?> 
				<div class="cart-compare-wishlist">                        
                <div class="cart-listing">  
                    <div class="cart-listing-inner">                         		                    
						<?php if($_product->isSaleable()): ?>
                         <a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">                         	
                            <span class="cart-text"><?php echo $this->__('Add to Cart') ?></span>
                          </a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                  </div>
                 </div>				    
			   <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <div class="compare-listing">                        
                        <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Compare'); ?>"><?php echo $this->__('Compare') ?></a>
                    </div>
                <?php endif; ?>	
                <?php if ($this->helper('wishlist')->isAllow() ) : ?>
                	<div class="wishlist-listing">
						<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn-wishlist" title="<?php echo $this->__('Add to Wishlist'); ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                    </div>
				<?php endif; ?>                               
				</div>
            </div>
            </div>
            <?php if($options->item_readmore_display == 1){?>
                <!--<div class="item-readmore">
                    <a href="<?php echo $item->link ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true"; title="<?php echo $item->title?>" data-arrow="&#187;" >
                        <?php //echo $options->item_readmore_text; ?>
                    </a>
                </div>-->
            <?php } ?>
						
							
            
		</div>
        </div>
	</div>
    
<?php } 
} ?>

