<?php
/*------------------------------------------------------------------------
 # SM Scrollbar - Version 1.0
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$tag_id = 'sm-scrollbar'.rand().time();
/*
$css = ob_get_contents();
?>
	#<?php echo $tag_id ?> .scrb-items{
		height:<?php echo $params->get('pane_height',380); ?>px;
	}

<?php 
$css = ob_get_contents();
ob_end_clean();
$document = JFactory::getDocument();
$document->addStyleDeclaration($css);
*/

$class_respl = 'respl01-'.$options->nb_column1 .' respl02-'.$options->nb_column2 .' respl03-'.$options->nb_column3 .' respl04-'.$options->nb_column4 ?>


<!--[if lt IE 9]><div id="<?php echo $tag_id; ?>" class="scrollbar-wrap  msie lt-ie9"><![endif]--> 
<!--[if IE 9]><div id="<?php echo $tag_id; ?>" class="scrollbar-wrap msie"><![endif]-->
 <!--[if gt IE 9]><!--><div id="<?php echo $tag_id; ?>" class="scrollbar-wrap "><!--<![endif]--> 
	<div  class="scrb-items cf <?php echo  $class_respl; ?>" style="height:<?php echo $options->pane_height; ?>px;">
		<?php $j=0; foreach($list as $item) { $j++; ?>
		<div class="scrb-item">
			<div class="scrb-item-inner">
				<div class="scrb-image">
					<a href="<?php echo $item['link']; ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true"; title="<?php echo $item['title'];?>" >
						<img src="<?php echo $item['image'];?>" alt="<?php echo $item['title']; ?>" title="<?php echo $item['title']; ?>" />
					</a>
				</div>
				<?php if( $options->product_title_disp == 1 && $item['title'] !='' ) { ?>
				<div class="scrb-title">
					<a href="<?php echo $item['link']; ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true"; title="<?php echo $item['title']?>" >
						<?php echo $item['title']; ?>
					</a>
				</div>
				<?php }
				if( $options->product_description_disp == 1 && $options->product_description_disp != '' ) { ?>
				<div class="scrb-desc">
					<?php echo $item['desc']; ?>
				</div>
				<?php }?>
				<?php if($options->product_reviews_count == 1){ ?>
					<div class="item-review">
						<?php echo $item['review']; ?>
					</div>
				<?php }					 
				if( (int)$options->product_price_disp ){ ?>
					<div class="item-price">
						<div class="sale-price">
						<?php echo $item['price'];?>
						</div>
					</div>
				<?php }?>
				<?php if( $options->product_details_page_link_disp == 1) {?>
				<div class="scrb-readmore">
					<a href="<?php echo $item['link']; ?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true"; title="<?php echo $item['title']; ?>" >
						<?php echo $options->product_details_page_link_text; ?>
					</a>
				</div>
				<?php } ?>
			</div>
		</div>
		<?php
			$clear = 'clr1';
			if ($j % 2 == 0) $clear .= ' clr2';
			if ($j % 3 == 0) $clear .= ' clr3';
			if ($j % 4 == 0) $clear .= ' clr4';
			if ($j % 5 == 0) $clear .= ' clr5';
			if ($j % 6 == 0) $clear .= ' clr6';
		?>
		<div class="<?php echo $clear; ?>"></div>   
		<?php } ?>
	</div>
 </div>
 
<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function($) {
	;(function(element){
		var $element = $(element);
		//(function($){
		//	$(window).load(function(){
				$(".scrb-items",$element).mCustomScrollbar({
					scrollInertia:550,
					horizontalScroll:false,
					mouseWheelPixels:116,
					autoDraggerLength:true,
					scrollButtons:{
						enable:<?php echo $show_arrows ?>,
						scrollAmount:116
					},
					 advanced:{
						updateOnContentResize: true
					},theme:"dark"
				});
		//	});
		//})(jQuery);
	})('#<?php echo $tag_id; ?>');
});	
//]]>	
</script>